{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rpf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rpf/rpf_{{ version }}.tar.gz
  sha256: a3c79afebb68e8233092994cbb3f5ac464316ffe7e4c5d87dfe0d5c070122248

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcppeigen
    - r-mvtnorm
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcppeigen
    - r-mvtnorm

test:
  commands:
    - $R -e "library('rpf')"           # [not win]
    - "\"%R%\" -e \"library('rpf')\""  # [win]

about:
  home: https://github.com/jpritikin/rpf
  license: GPL (>= 3)
  summary: The purpose of this package is to factor out logic and math common to Item Factor
    Analysis fitting, diagnostics, and analysis. It is envisioned as core support code
    suitable for more specialized IRT packages to build upon. Complete access to optimized
    C functions are made available with R_RegisterCCallable().
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Encoding: UTF-8
# Package: rpf
# Type: Package
# Title: Response Probability Functions
# Version: 0.62
# Date: 2019-04-12
# Authors@R: c(person("Joshua",family="Pritikin", email="jpritikin@pobox.com", role=c('cre','aut')), person("Jonathan",family="Weeks", email="weeksjp@gmail.com", role=c('ctb')), person("Li", family="Cai", role=c('ctb')), person("Carrie", family="Houts", role=c('ctb')), person("Phil", "Chalmers", email = "rphilip.chalmers@gmail.com", role = c("ctb")), person(c("Michael", "D."), "Hunter", role="ctb"), person(c("Carl", "F."), "Falk", email = "falkcarl@msu.edu", role = c("ctb")) )
# Maintainer: Joshua Pritikin <jpritikin@pobox.com>
# Description: The purpose of this package is to factor out logic and math common to Item Factor Analysis fitting, diagnostics, and analysis. It is envisioned as core support code suitable for more specialized IRT packages to build upon. Complete access to optimized C functions are made available with R_RegisterCCallable().
# LazyData: yes
# LazyDataCompression: bzip2
# License: GPL (>= 3)
# LinkingTo: RcppEigen
# Suggests: testthat, roxygen2, ggplot2, reshape2, gridExtra, numDeriv, knitr, mirt
# Imports: mvtnorm
# Depends: methods, parallel, R (>= 2.14.0)
# VignetteBuilder: knitr
# Collate: 'init.R' 'classes.R' 'fit.R' 'drm.R' 'nrm.R' 'mcm.R' 'grm.R' 'LSAT.R' 'sample.R' 'dataframe.R' 'diagnose.R' 'science.R' 'kct.R' 'openmx.R' 'flexmirt.R' 'util.R' 'lmp.R'
# URL: https://github.com/jpritikin/rpf
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-04-12 18:35:16 UTC; joshua
# Author: Joshua Pritikin [cre, aut], Jonathan Weeks [ctb], Li Cai [ctb], Carrie Houts [ctb], Phil Chalmers [ctb], Michael D. Hunter [ctb], Carl F. Falk [ctb]
# Repository: CRAN
# Date/Publication: 2019-04-12 19:22:43 UTC
